// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnMSy7bSGQH8H5Ekbr44a0vDr25GPooH0',
    appId: '1:446863295792:web:a24f2291df2e99a1fa74f5',
    messagingSenderId: '446863295792',
    projectId: 'ecommerce-app-cdcda',
    authDomain: 'ecommerce-app-cdcda.firebaseapp.com',
    storageBucket: 'ecommerce-app-cdcda.firebasestorage.app',
    measurementId: 'G-SETMJM0EYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADINHX0noyBRKOK_URPHD5Tqw_Rpfo3E0',
    appId: '1:446863295792:android:65d3180d7cf757e5fa74f5',
    messagingSenderId: '446863295792',
    projectId: 'ecommerce-app-cdcda',
    storageBucket: 'ecommerce-app-cdcda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiR-tKWTtG0Xf5NQk-MNnFJcC7Zoe11jY',
    appId: '1:446863295792:ios:ecbf8d58a29d2a82fa74f5',
    messagingSenderId: '446863295792',
    projectId: 'ecommerce-app-cdcda',
    storageBucket: 'ecommerce-app-cdcda.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiR-tKWTtG0Xf5NQk-MNnFJcC7Zoe11jY',
    appId: '1:446863295792:ios:ecbf8d58a29d2a82fa74f5',
    messagingSenderId: '446863295792',
    projectId: 'ecommerce-app-cdcda',
    storageBucket: 'ecommerce-app-cdcda.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
